### ISSUE TITLE
Click and drag menu from toggle button. Selects but does not show selected.

### ISSUE THREAD

**Issue by PierceDrawboard** [CatalystCode/radial-menu#103] opened 2015-10-15 06:35 UTC

**Comment by felixrieseberg** [comment] 2015-10-15 20:54
We can't reproduce?

**Comment by PierceDrawboard** [comment] 2015-10-15 22:22
Hmm, it might be my implementation. It fires the InnerArcPressed on mouse down, which is what I used to select the tool. If you then move the mouse and drag the control to an edge so that the mouse up event does not happen over the button, the tool is not selected on the UI. So the view has lost sync with the viewmodel. Maybe just make it select on mousedown instead of mouse up?

**Comment by sedouard** [comment] 2015-10-16 03:30
closed via https://github.com/CatalystCode/radial-menu/pull/118

**Closed as completed by sedouard** 2015-10-16 03:30 UTC
